/* Automatically generated by po2tbl.sed from gtksee.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"ok", 2},
  {"Problem deleting file!", 3},
  {"Remove", 4},
  {"Do you really want to remove %i file(s) ?", 5},
  {"yes", 6},
  {"no", 7},
  {"Problem in rename file!", 8},
  {"File exist !", 9},
  {"Same filename !", 10},
  {"No filename !", 11},
  {"Rename", 12},
  {"Rename file:", 13},
  {"cancel", 14},
  {"Impossible to rename the files", 15},
  {"-adobe-helvetica-bold-r-normal--*-180-*-*-*-*-*-*", 16},
  {"-adobe-times-medium-r-normal--*-140-*-*-*-*-*-*", 17},
  {"O K", 18},
  {"Total %i file(s) (%s)", 19},
  {"\
\n\
(c)1998-? Lee Luyang(Hotaru), China", 20},
  {"This software is distributed under", 21},
  {"GPL Version 2", 22},
  {"See the 'COPYING' file for details\n", 23},
  {"File", 24},
  {"View", 25},
  {"Full-view", 26},
  {"Quit", 27},
  {"Edit", 28},
  {"Cut", 29},
  {"Copy", 30},
  {"Paste", 31},
  {"Paste hard-link", 32},
  {"Delete", 33},
  {"Select all", 34},
  {"Thumbnails", 35},
  {"Small icons", 36},
  {"Details", 37},
  {"Show hidden files", 38},
  {"Hide non-images", 39},
  {"Fast preview", 40},
  {"Sort", 41},
  {"By Name", 42},
  {"By Size", 43},
  {"By Property", 44},
  {"By Date", 45},
  {"By Type", 46},
  {"Ascend", 47},
  {"Descend", 48},
  {"Refresh", 49},
  {"Quick-refresh", 50},
  {"Auto-refresh", 51},
  {"Tools", 52},
  {"Slide show", 53},
  {"The Gimp", 54},
  {"Options...", 55},
  {"Help", 56},
  {"Legal", 57},
  {"Usage", 58},
  {"Known-bugs", 59},
  {"Feedback", 60},
  {"About", 61},
  {"\
    GTK See is free software; you can redistribute it and/or modify it under \
the terms of the GNU General Public License as published by the Free \
Software Foundation; either version 2 of the License, or (at your option) \
any later version.\n\
\n", 62},
  {"\
    GTK See is distributed in the hope that it will be useful, but WITHOUT \
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or \
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for \
more details.\n\
\n", 63},
  {"\
    You should have received a copy of the GNU General Public License along \
with this program; if not, write to the Free Software Foundation, Inc., 59 \
Temple Place - Suite 330, Boston, MA 02111-1307, USA.\n", 64},
  {"Command-line usage:\n", 65},
  {"    gtksee [-R[directory]] [-fis] [files...]\n", 66},
  {"      -r  --  Use current directory as root\n", 67},
  {"      -R<directory>  --  Use <directory> as root\n", 68},
  {"      -f  --  Enable full-screen mode\n", 69},
  {"      -i  --  Enable fit-screen mode\n", 70},
  {"      -s  --  Enable slide-show mode\n", 71},
  {"      files... --  Launch gtksee viewer\n", 72},
  {"\
      -h  --  Print help messages\n\
\n", 73},
  {"Keyboard shortcuts:\n", 74},
  {"    These keys are bound to viewer:\n", 75},
  {"    [Arrow-keys] Move large image\n", 76},
  {"    [PageUp] Show previous image\n", 77},
  {"    [PageDown] Show next image\n", 78},
  {"    [Home] Show the first image\n", 79},
  {"    [End] Show the last image\n", 80},
  {"    [Space] Show next image(loop)\n", 81},
  {"\
    [Escape] Return to the browser\n\
\n", 82},
  {"Mouse hints:\n", 83},
  {"\
    In view mode, double-click on the image to return to the browser.\n\
\n", 84},
  {"Have fun!\n", 85},
  {"None :)\n", 86},
  {"Comments, suggestions and bug-reportings:\n", 87},
  {"    Please send them to my current primary e-mail address:\n", 88},
  {"\
    I'm always collecting all kinds of images. If you *really* like this \
program, send your favorite picture(s) to my secondary e-mail address:\n", 89},
  {"\
    Keep sending me things. :) And I'll keep on developing this program.\n", 90},
  {"    P.S. My favorite is Anime/Manga. :)\n", 91},
  {"Up One Level", 92},
  {"Name ", 93},
  {"Size ", 94},
  {"Image Properties ", 95},
  {"Type ", 96},
  {"Options", 97},
  {"Root directory", 98},
  {"Hidden directories", 99},
  {"File System", 100},
  {"Interval", 101},
  {"Slide Show", 102},
  {" Cancel ", 103},
  {" O K ", 104},
  {"second(s)", 105},
  {"minute(s)", 106},
  {"hour(s)", 107},
  {"day(s)", 108},
  {"milliseconds, no delay", 109},
  {"milliseconds, %i %s", 110},
  {"Invalid", 111},
  {"Next image", 112},
  {"Previous image", 113},
  {"Fit screen", 114},
  {"Full screen", 115},
  {"Browser", 116},
  {"Exit", 117},
  {"Browse", 118},
  {"Previous Image", 119},
  {"Next Image", 120},
  {"Stop/Resume Slideshow", 121},
  {"Fit Screen", 122},
  {"Rotate -90", 123},
  {"Rotate +90", 124},
};

int _msg_tbl_length = 124;
