/* Automatically generated by po2tbl.sed from gtksee.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Remove", 2},
  {"Do you really want to remove:", 3},
  {"yes", 4},
  {"no", 5},
  {"Rename", 6},
  {"Rename file:", 7},
  {"ok", 8},
  {"cancel", 9},
  {"-adobe-helvetica-bold-r-normal--*-180-*-*-*-*-*-*", 10},
  {"-adobe-times-medium-r-normal--*-140-*-*-*-*-*-*", 11},
  {"O K", 12},
  {"Total %i file(s) (%s)", 13},
  {"(c)1998-? Lee Luyang(Hotaru), China", 14},
  {"This software is distributed under", 15},
  {"GPL Version 2", 16},
  {"File", 17},
  {"View", 18},
  {"Full-view", 19},
  {"Quit", 20},
  {"Edit", 21},
  {"Cut", 22},
  {"Copy", 23},
  {"Paste", 24},
  {"Paste hard-link", 25},
  {"Delete", 26},
  {"Select all", 27},
  {"Thumbnails", 28},
  {"Small icons", 29},
  {"Details", 30},
  {"Show hidden files", 31},
  {"Hide non-images", 32},
  {"Fast preview", 33},
  {"Sort", 34},
  {"By Name", 35},
  {"By Size", 36},
  {"By Property", 37},
  {"By Date", 38},
  {"Ascend", 39},
  {"Descend", 40},
  {"Refresh", 41},
  {"Quick-refresh", 42},
  {"Auto-refresh", 43},
  {"Tools", 44},
  {"Slide show", 45},
  {"The Gimp", 46},
  {"Options...", 47},
  {"Help", 48},
  {"Legal", 49},
  {"Usage", 50},
  {"Known-bugs", 51},
  {"Feedback", 52},
  {"About", 53},
  {"\
    GTK See is free software; you can redistribute it and/or modify it under \
the terms of the GNU General Public License as published by the Free \
Software Foundation; either version 2 of the License, or (at your option) \
any later version.\n\
\n", 54},
  {"\
    GTK See is distributed in the hope that it will be useful, but WITHOUT \
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or \
FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for \
more details.\n\
\n", 55},
  {"\
    You should have received a copy of the GNU General Public License along \
with this program; if not, write to the Free Software Foundation, Inc., 59 \
Temple Place - Suite 330, Boston, MA 02111-1307, USA.\n", 56},
  {"Command-line usage:\n", 57},
  {"    gtksee [-R[directory]] [-fis] [files...]\n", 58},
  {"      -R  --  Use current directory as root\n", 59},
  {"      -R<directory>  --  Use <directory> as root\n", 60},
  {"      -f  --  Enable full-screen mode\n", 61},
  {"      -i  --  Enable fit-screen mode\n", 62},
  {"      -s  --  Enable slide-show mode\n", 63},
  {"      files... --  Launch gtksee viewer\n", 64},
  {"\
      -h  --  Print help messages\n\
\n", 65},
  {"Keyboard shortcuts:\n", 66},
  {"    These keys are bound to viewer:\n", 67},
  {"    [Arrow-keys] Move large image\n", 68},
  {"    [PageUp] Show previous image\n", 69},
  {"    [PageDown] Show next image\n", 70},
  {"    [Home] Show the first image\n", 71},
  {"    [End] Show the last image\n", 72},
  {"    [Space] Show next image(loop)\n", 73},
  {"\
    [Escape] Return to the browser\n\
\n", 74},
  {"Mouse hints:\n", 75},
  {"\
    In view mode, double-click on the image to return to the browser.\n\
\n", 76},
  {"Have fun!\n", 77},
  {"None :)\n", 78},
  {"Comments, suggestions and bug-reportings:\n", 79},
  {"    Please send them to my current primary e-mail address:\n", 80},
  {"\
    I'm always collecting all kinds of images. If you *really* like this \
program, send your favorite picture(s) to my secondary e-mail address:\n", 81},
  {"\
    Keep sending me things. :) And I'll keep on developing this program.\n", 82},
  {"    P.S. My favorite is Anime/Manga. :)\n", 83},
  {"Up One Level", 84},
  {"Name ", 85},
  {"Size ", 86},
  {"Image Properties ", 87},
  {"Options", 88},
  {"Root directory", 89},
  {"Hidden directories", 90},
  {"File System", 91},
  {"Interval", 92},
  {"Slide Show", 93},
  {" Cancel ", 94},
  {" O K ", 95},
  {"second(s)", 96},
  {"minute(s)", 97},
  {"hour(s)", 98},
  {"day(s)", 99},
  {"milliseconds, no delay", 100},
  {"milliseconds, %i %s", 101},
  {"Invalid", 102},
  {"Next image", 103},
  {"Previous image", 104},
  {"Fit screen", 105},
  {"Full screen", 106},
  {"Browser", 107},
  {"Exit", 108},
  {"Browse", 109},
  {"Previous Image", 110},
  {"Next Image", 111},
  {"Stop/Resume Slideshow", 112},
  {"Fit Screen", 113},
  {"Rotate -90", 114},
  {"Rotate +90", 115},
};

int _msg_tbl_length = 115;
